/**
 * Card Show Finder — static data + zip-to-distance logic.
 *
 * Major / regional shows only. Not every small mall show — these are
 * the ones worth traveling for.
 *
 * Sources: CardShowHub, Hall of Cards, Sports Collectors Digest,
 *          individual show websites, Beckett.
 */

// ── Types ──────────────────────────────────────────────────────────

export type ShowSize = 'mega' | 'major' | 'regional';

export interface CardShow {
  id: string;
  name: string;
  /** City, State */
  location: string;
  venue: string;
  /** Latitude for distance calc */
  lat: number;
  /** Longitude for distance calc */
  lng: number;
  /** ISO date strings — null if TBA */
  startDate: string | null;
  endDate: string | null;
  /** How often it repeats — null if one-off */
  recurrence: string | null;
  /** Approximate dealer table count */
  tables: number | null;
  size: ShowSize;
  /** Link to official site or event page */
  url: string | null;
  /** One-liner about the show */
  description: string;
  /** General admission price, or null if free/unknown */
  admissionPrice: string | null;
}

// ── Show Data ──────────────────────────────────────────────────────

export const CARD_SHOWS: CardShow[] = [
  // ═══ MEGA (1000+ tables / national significance) ═══

  {
    id: 'nscc-2026',
    name: 'The National (NSCC)',
    location: 'Rosemont, IL',
    venue: 'Donald E. Stephens Convention Center',
    lat: 41.9842,
    lng: -87.8643,
    startDate: '2026-07-29',
    endDate: '2026-08-02',
    recurrence: 'Annual (late July)',
    tables: 800,
    size: 'mega',
    url: 'https://www.nsccshow.com',
    description: 'The Super Bowl of card shows. 800+ booths, every major brand, grading companies, and 40,000+ attendees. The biggest event in the hobby.',
    admissionPrice: '$30',
  },
  {
    id: 'dallas-mar-2026',
    name: 'Dallas Card Show',
    location: 'Allen, TX',
    venue: 'Delta Hotels by Marriott Dallas Allen',
    lat: 33.1032,
    lng: -96.6706,
    startDate: '2026-03-12',
    endDate: '2026-03-15',
    recurrence: '6x per year',
    tables: 700,
    size: 'mega',
    url: 'https://www.dallascardshow.com',
    description: 'One of the largest regional shows in the country. 700+ tables, auction houses, PSA/BGS grading on-site, and Trade Night.',
    admissionPrice: '$15',
  },
  {
    id: 'dallas-jun-2026',
    name: 'Dallas Card Show',
    location: 'Allen, TX',
    venue: 'Delta Hotels by Marriott Dallas Allen',
    lat: 33.1032,
    lng: -96.6706,
    startDate: '2026-06-11',
    endDate: '2026-06-14',
    recurrence: '6x per year',
    tables: 700,
    size: 'mega',
    url: 'https://www.dallascardshow.com',
    description: 'One of the largest regional shows in the country. 700+ tables, auction houses, PSA/BGS grading on-site, and Trade Night.',
    admissionPrice: '$15',
  },
  {
    id: 'dallas-sep-2026',
    name: 'Dallas Card Show',
    location: 'Allen, TX',
    venue: 'Delta Hotels by Marriott Dallas Allen',
    lat: 33.1032,
    lng: -96.6706,
    startDate: '2026-09-10',
    endDate: '2026-09-13',
    recurrence: '6x per year',
    tables: 700,
    size: 'mega',
    url: 'https://www.dallascardshow.com',
    description: 'One of the largest regional shows in the country. 700+ tables, auction houses, PSA/BGS grading on-site, and Trade Night.',
    admissionPrice: '$15',
  },

  // ═══ MAJOR (200–500 tables / multi-day) ═══

  {
    id: 'wccs-feb-2026',
    name: 'West Coast Card Show',
    location: 'Ontario, CA',
    venue: 'Ontario Convention Center',
    lat: 34.0633,
    lng: -117.6509,
    startDate: '2026-02-12',
    endDate: '2026-02-15',
    recurrence: '2-3x per year',
    tables: 500,
    size: 'major',
    url: 'https://westcoastcardshow.com',
    description: 'West Coast flagship show. 500+ tables across sports, Pokémon, and entertainment. The epicenter of SoCal card culture.',
    admissionPrice: '$20',
  },
  {
    id: 'wccs-may-2026',
    name: 'West Coast Card Show',
    location: 'Ontario, CA',
    venue: 'Ontario Convention Center',
    lat: 34.0633,
    lng: -117.6509,
    startDate: '2026-05-28',
    endDate: '2026-05-31',
    recurrence: '2-3x per year',
    tables: 500,
    size: 'major',
    url: 'https://westcoastcardshow.com',
    description: 'West Coast flagship show. 500+ tables across sports, Pokémon, and entertainment. The epicenter of SoCal card culture.',
    admissionPrice: '$20',
  },
  {
    id: 'philly-apr-2026',
    name: 'Philly Card Show',
    location: 'Philadelphia, PA',
    venue: 'Greater Philadelphia Expo Center',
    lat: 40.1851,
    lng: -75.2499,
    startDate: '2026-04-11',
    endDate: '2026-04-12',
    recurrence: '2x per year',
    tables: 250,
    size: 'major',
    url: null,
    description: '250+ tables in the heart of the East Coast card market. Strong vintage presence and regional dealers.',
    admissionPrice: '$10',
  },
  {
    id: 'philly-nov-2026',
    name: 'Philly Non-Sports & Sports Card Show',
    location: 'Fort Washington, PA',
    venue: 'Fort Washington Expo Center',
    lat: 40.1382,
    lng: -75.2071,
    startDate: '2026-11-07',
    endDate: '2026-11-08',
    recurrence: 'Annual (fall)',
    tables: 300,
    size: 'major',
    url: null,
    description: '300+ tables. One of the East Coast\'s largest fall shows. Mix of sports and non-sports cards.',
    admissionPrice: '$10',
  },
  {
    id: 'ne-expo-may-2026',
    name: 'Northeast Sports Card Expo',
    location: 'Stamford, CT',
    venue: 'Chelsea Piers: Stamford',
    lat: 41.0534,
    lng: -73.5387,
    startDate: '2026-05-02',
    endDate: '2026-05-03',
    recurrence: '2-3x per year',
    tables: 200,
    size: 'major',
    url: 'https://www.northeastcardexpo.com',
    description: 'Premier Northeast show. 200+ tables, grading on-site, autograph guests. Early entry available.',
    admissionPrice: '$15',
  },
  {
    id: 'ne-expo-sep-2026',
    name: 'Northeast Sports Card Expo',
    location: 'Stamford, CT',
    venue: 'Chelsea Piers: Stamford',
    lat: 41.0534,
    lng: -73.5387,
    startDate: '2026-09-12',
    endDate: '2026-09-13',
    recurrence: '2-3x per year',
    tables: 200,
    size: 'major',
    url: 'https://www.northeastcardexpo.com',
    description: 'Premier Northeast show. 200+ tables, grading on-site, autograph guests. Early entry available.',
    admissionPrice: '$15',
  },
  {
    id: 'lv-feb-2026',
    name: 'Las Vegas Card Show',
    location: 'Las Vegas, NV',
    venue: 'Las Vegas Convention Center',
    lat: 36.1281,
    lng: -115.1527,
    startDate: '2026-02-07',
    endDate: '2026-02-09',
    recurrence: '2x per year',
    tables: 200,
    size: 'major',
    url: null,
    description: '200+ tables timed around Super Bowl LXI. Dealers bring heavy vintage and modern football inventory.',
    admissionPrice: '$15',
  },
  {
    id: 'houston-may-2026',
    name: 'Houston Card Show',
    location: 'Houston, TX',
    venue: 'NRG Center',
    lat: 29.6847,
    lng: -95.4107,
    startDate: '2026-05-16',
    endDate: '2026-05-17',
    recurrence: '2-3x per year',
    tables: 200,
    size: 'major',
    url: null,
    description: '200+ tables with autograph guests. Major hub for Texas collectors outside of Dallas.',
    admissionPrice: '$10',
  },
  {
    id: 'chicago-nov-2026',
    name: 'Chicago Card Show',
    location: 'Chicago, IL',
    venue: 'Odeum Expo Center',
    lat: 41.7508,
    lng: -88.1535,
    startDate: '2026-11-21',
    endDate: '2026-11-22',
    recurrence: 'Annual (fall)',
    tables: 225,
    size: 'major',
    url: null,
    description: '225+ tables. Chicago\'s largest non-National show. Strong Midwest dealer attendance.',
    admissionPrice: '$10',
  },
  {
    id: 'megafest-mar-2026',
    name: 'Trading Card Megafest Explosion',
    location: 'Hollywood, FL',
    venue: 'Seminole Hard Rock Hotel & Casino',
    lat: 26.0510,
    lng: -80.2104,
    startDate: '2026-03-14',
    endDate: '2026-03-15',
    recurrence: 'Annual',
    tables: 250,
    size: 'major',
    url: null,
    description: '250+ tables at the Hard Rock. South Florida\'s flagship card show with celebrity autograph sessions.',
    admissionPrice: '$15',
  },

  // ═══ REGIONAL (100–200 tables / 1-2 day) ═══

  {
    id: 'az-spring-2026',
    name: 'Arizona State Card Show',
    location: 'Phoenix, AZ',
    venue: 'Arizona State Fairgrounds',
    lat: 33.4676,
    lng: -112.0975,
    startDate: '2026-03-07',
    endDate: '2026-03-08',
    recurrence: 'Annual (Spring Training)',
    tables: 150,
    size: 'regional',
    url: null,
    description: 'Timed with MLB Spring Training. Strong baseball focus with vintage and autograph dealers.',
    admissionPrice: '$10',
  },
  {
    id: 'atlanta-may-2026',
    name: 'Atlanta Card Show',
    location: 'Atlanta, GA',
    venue: 'Gas South Convention Center',
    lat: 33.9617,
    lng: -84.0683,
    startDate: '2026-05-09',
    endDate: '2026-05-10',
    recurrence: '2-3x per year',
    tables: 150,
    size: 'regional',
    url: null,
    description: 'Southeast hub show. 150+ tables with strong basketball and football inventory.',
    admissionPrice: '$10',
  },
  {
    id: 'bay-area-apr-2026',
    name: 'Bay Area Sports Card Show',
    location: 'San Jose, CA',
    venue: 'Santa Clara Convention Center',
    lat: 37.3939,
    lng: -121.9746,
    startDate: '2026-04-18',
    endDate: '2026-04-19',
    recurrence: '2x per year',
    tables: 150,
    size: 'regional',
    url: null,
    description: 'NorCal\'s biggest show. 150+ tables with Bay Area dealers and grading services.',
    admissionPrice: '$10',
  },
  {
    id: 'seattle-jun-2026',
    name: 'Seattle Card Show',
    location: 'Seattle, WA',
    venue: 'Seattle Convention Center',
    lat: 47.6115,
    lng: -122.3317,
    startDate: '2026-06-20',
    endDate: '2026-06-21',
    recurrence: '2x per year',
    tables: 120,
    size: 'regional',
    url: null,
    description: 'Pacific Northwest hub. Growing show with 120+ tables and strong basketball focus.',
    admissionPrice: '$10',
  },
  {
    id: 'denver-apr-2026',
    name: 'Mile High Card Show',
    location: 'Denver, CO',
    venue: 'National Western Complex',
    lat: 39.7817,
    lng: -104.9719,
    startDate: '2026-04-25',
    endDate: '2026-04-26',
    recurrence: '2x per year',
    tables: 130,
    size: 'regional',
    url: null,
    description: 'Rocky Mountain region\'s primary show. Growing fast with 130+ tables.',
    admissionPrice: '$8',
  },
  {
    id: 'detroit-may-2026',
    name: 'Motor City Card Show',
    location: 'Novi, MI',
    venue: 'Suburban Collection Showplace',
    lat: 42.4809,
    lng: -83.4755,
    startDate: '2026-05-30',
    endDate: '2026-05-31',
    recurrence: '2x per year',
    tables: 150,
    size: 'regional',
    url: null,
    description: 'Michigan\'s biggest show. 150+ tables with strong vintage baseball and hockey presence.',
    admissionPrice: '$10',
  },
  {
    id: 'minneapolis-jun-2026',
    name: 'Twin Cities Card Show',
    location: 'Minneapolis, MN',
    venue: 'Minneapolis Convention Center',
    lat: 44.9692,
    lng: -93.2735,
    startDate: '2026-06-06',
    endDate: '2026-06-07',
    recurrence: '2x per year',
    tables: 120,
    size: 'regional',
    url: null,
    description: 'Upper Midwest hub. 120+ tables with strong hockey and football inventory.',
    admissionPrice: '$8',
  },
  {
    id: 'nashville-apr-2026',
    name: 'Nashville Card Show',
    location: 'Nashville, TN',
    venue: 'Nashville Fairgrounds',
    lat: 36.1341,
    lng: -86.7631,
    startDate: '2026-04-04',
    endDate: '2026-04-05',
    recurrence: '2x per year',
    tables: 100,
    size: 'regional',
    url: null,
    description: 'Growing mid-South show. 100+ tables with diverse sports mix.',
    admissionPrice: '$8',
  },

  // ═══ NEW — sourced from Hall of Cards, CardShowHub, TCDB ═══

  {
    id: 'strongsville-jan-2026',
    name: 'Strongsville Sports Cards & Collectibles Show',
    location: 'Strongsville, OH',
    venue: 'Ehrnfelt Recreation Center',
    lat: 41.3145,
    lng: -81.8357,
    startDate: '2026-01-18',
    endDate: '2026-01-19',
    recurrence: '2x per year',
    tables: 150,
    size: 'regional',
    url: null,
    description: '150+ tables. One of Northeast Ohio\'s largest recurring shows with strong vintage baseball presence.',
    admissionPrice: '$8',
  },
  {
    id: 'tampa-mar-2026',
    name: 'Tampa Bay SportsCollectors Expo',
    location: 'Tampa, FL',
    venue: 'Tampa Convention Center',
    lat: 27.9420,
    lng: -82.4572,
    startDate: '2026-03-13',
    endDate: '2026-03-15',
    recurrence: '2x per year',
    tables: 200,
    size: 'major',
    url: null,
    description: '200+ tables. Florida\'s largest sports card show with autograph guests and grading on-site.',
    admissionPrice: '$10',
  },
  {
    id: 'jacksonville-mar-2026',
    name: 'Jacksonville Card Show',
    location: 'Jacksonville, FL',
    venue: 'Adam W. Herbert University Center',
    lat: 30.2721,
    lng: -81.5074,
    startDate: '2026-03-13',
    endDate: '2026-03-14',
    recurrence: 'Monthly',
    tables: 150,
    size: 'regional',
    url: null,
    description: '150+ tables. Recurring monthly show in North Florida with growing attendance.',
    admissionPrice: '$5',
  },
  {
    id: 'orlando-apr-2026',
    name: 'The Orlando Card Show',
    location: 'Apopka, FL',
    venue: 'The Orlando Card Show Venue',
    lat: 28.6934,
    lng: -81.5322,
    startDate: '2026-04-17',
    endDate: '2026-04-18',
    recurrence: 'Monthly',
    tables: 100,
    size: 'regional',
    url: null,
    description: '100+ tables. Central Florida\'s go-to monthly show. Friday evening + Saturday format.',
    admissionPrice: '$5',
  },
  {
    id: 'secaucus-mar-2026',
    name: 'East Coast Sports Cards Expo',
    location: 'Secaucus, NJ',
    venue: 'La Quinta Inn & Suites',
    lat: 40.7893,
    lng: -74.0565,
    startDate: '2026-03-12',
    endDate: '2026-03-15',
    recurrence: '3-4x per year',
    tables: 120,
    size: 'regional',
    url: null,
    description: '120+ tables right across from NYC. Easy access for Manhattan and North Jersey collectors.',
    admissionPrice: '$10',
  },
  {
    id: 'secaucus-jun-2026',
    name: 'East Coast Sports Cards Expo',
    location: 'Secaucus, NJ',
    venue: 'La Quinta Inn & Suites',
    lat: 40.7893,
    lng: -74.0565,
    startDate: '2026-06-06',
    endDate: '2026-06-07',
    recurrence: '3-4x per year',
    tables: 275,
    size: 'major',
    url: null,
    description: '275+ tables. Largest East Coast show outside of Philly. Strong NYC metro dealer base.',
    admissionPrice: '$10',
  },
  {
    id: 'great-american-apr-2026',
    name: 'The Great American Sports Memorabilia & Trading Card Show',
    location: 'Xenia, OH',
    venue: 'Greene County Fairgrounds',
    lat: 39.6845,
    lng: -83.9293,
    startDate: '2026-04-04',
    endDate: '2026-04-04',
    recurrence: 'Monthly',
    tables: 400,
    size: 'mega',
    url: null,
    description: '400+ tables. One of the largest single-day shows in the country. Massive Ohio collector community.',
    admissionPrice: '$5',
  },
  {
    id: 'great-lakes-apr-2026',
    name: 'Great Lakes Collectors Convention',
    location: 'Independence, OH',
    venue: 'Independence Civic Center Field House',
    lat: 41.3812,
    lng: -81.6382,
    startDate: '2026-04-11',
    endDate: '2026-04-12',
    recurrence: '2x per year',
    tables: 250,
    size: 'major',
    url: null,
    description: '250+ tables. Northeast Ohio\'s premier multi-day show with strong vintage and modern mix.',
    admissionPrice: '$10',
  },
  {
    id: 'cleveland-oct-2026',
    name: 'Cleveland Sports Legends & Memorabilia Show',
    location: 'Cleveland, OH',
    venue: 'I-X Center',
    lat: 41.4070,
    lng: -81.8042,
    startDate: '2026-10-10',
    endDate: '2026-10-11',
    recurrence: 'Annual (fall)',
    tables: 150,
    size: 'regional',
    url: null,
    description: '150+ tables. Cleveland\'s fall classic with autograph signings and grading services.',
    admissionPrice: '$10',
  },
  {
    id: 'albany-monthly-2026',
    name: 'Polish Community Center Card Show',
    location: 'Albany, NY',
    venue: 'Polish Community Center',
    lat: 42.6526,
    lng: -73.7562,
    startDate: '2026-04-18',
    endDate: '2026-04-18',
    recurrence: 'Monthly',
    tables: 110,
    size: 'regional',
    url: null,
    description: '110+ tables. Albany\'s flagship monthly show. Consistent dealer lineup with Upstate NY collectors.',
    admissionPrice: '$5',
  },
  {
    id: 'milwaukee-jun-2026',
    name: 'Milwaukee Sports Collectors Show',
    location: 'Milwaukee, WI',
    venue: 'Wisconsin State Fair Park',
    lat: 43.0186,
    lng: -88.0070,
    startDate: '2026-06-20',
    endDate: '2026-06-21',
    recurrence: 'Annual',
    tables: 125,
    size: 'regional',
    url: null,
    description: '125+ tables. Wisconsin\'s biggest show with strong Packers and Brewers card inventory.',
    admissionPrice: '$8',
  },
  {
    id: 'dallas-apr-2026',
    name: 'Dallas Card Show',
    location: 'Allen, TX',
    venue: 'Delta Hotels by Marriott Dallas Allen',
    lat: 33.1032,
    lng: -96.6706,
    startDate: '2026-04-25',
    endDate: '2026-04-26',
    recurrence: '6x per year',
    tables: 700,
    size: 'mega',
    url: 'https://www.dallascardshow.com',
    description: 'One of the largest regional shows in the country. 700+ tables, auction houses, PSA/BGS grading on-site, and Trade Night.',
    admissionPrice: '$15',
  },
  {
    id: 'wildwood-jul-2026',
    name: 'Wildwood Card Show',
    location: 'Wildwood, NJ',
    venue: 'Wildwoods Convention Center',
    lat: 38.9810,
    lng: -74.8148,
    startDate: '2026-07-03',
    endDate: '2026-07-04',
    recurrence: '2x per year',
    tables: 200,
    size: 'major',
    url: null,
    description: '200+ tables on the Jersey Shore for July 4th weekend. Vacation + card show combo.',
    admissionPrice: '$10',
  },
  {
    id: 'mt-kisco-mar-2026',
    name: 'Westchester Sports Card Show',
    location: 'Mount Kisco, NY',
    venue: 'Boys & Girls Club of Northern Westchester',
    lat: 41.2040,
    lng: -73.7271,
    startDate: '2026-03-15',
    endDate: '2026-03-15',
    recurrence: 'Quarterly',
    tables: 70,
    size: 'regional',
    url: null,
    description: '70+ tables. Convenient Westchester County location for NYC-area collectors.',
    admissionPrice: '$5',
  },
  {
    id: 'cincinnati-eastgate-mar-2026',
    name: 'Eastgate Mall Sports Cards & Pokemon Show',
    location: 'Cincinnati, OH',
    venue: 'Eastgate Mall',
    lat: 39.0982,
    lng: -84.2802,
    startDate: '2026-03-21',
    endDate: '2026-03-21',
    recurrence: 'Monthly',
    tables: 400,
    size: 'mega',
    url: null,
    description: '400+ tables. Cincinnati\'s massive mall show covering sports cards and Pokémon. One of Ohio\'s largest.',
    admissionPrice: '$5',
  },
  {
    id: 'grove-city-mar-2026',
    name: 'Grove City Card Fest',
    location: 'Grove City, OH',
    venue: 'Grove City Church of the Nazarene',
    lat: 39.8812,
    lng: -83.0930,
    startDate: '2026-03-22',
    endDate: '2026-03-22',
    recurrence: 'Monthly',
    tables: 300,
    size: 'major',
    url: null,
    description: '300+ tables. Central Ohio powerhouse show. Fast-growing with strong collector turnout.',
    admissionPrice: '$5',
  },
  {
    id: 'lake-erie-apr-2026',
    name: 'Lake Erie Card Convention (LECC)',
    location: 'Painesville, OH',
    venue: 'Lake County Fairgrounds',
    lat: 41.7242,
    lng: -81.2457,
    startDate: '2026-04-25',
    endDate: '2026-04-25',
    recurrence: '2x per year',
    tables: 150,
    size: 'regional',
    url: null,
    description: '150+ tables. Northeast Ohio convention-style show with trading pits and breaks area.',
    admissionPrice: '$8',
  },

  // ═══ WAVE 2 — sourced from SCD, CardShowHub, Hall of Cards ═══

  // ── MEGA (400+ tables) ──

  {
    id: 'cabarrus-jun-2026',
    name: 'Cabarrus Arena Card Show',
    location: 'Concord, NC',
    venue: 'Cabarrus Arena & Events Center',
    lat: 35.3948,
    lng: -80.6312,
    startDate: '2026-06-05',
    endDate: '2026-06-07',
    recurrence: 'Annual',
    tables: 600,
    size: 'mega',
    url: null,
    description: '600 tables. One of the largest shows on the East Coast. Full convention experience in the Charlotte metro.',
    admissionPrice: '$10',
  },
  {
    id: 'hubcity-sep-2026',
    name: 'Hub City CardXpo',
    location: 'Hagerstown, MD',
    venue: 'Hagerstown Field House',
    lat: 39.6418,
    lng: -77.7200,
    startDate: '2026-09-05',
    endDate: '2026-09-06',
    recurrence: 'Annual',
    tables: 600,
    size: 'mega',
    url: null,
    description: '600+ tables. Maryland\'s largest trading card expo — sports cards, TCGs, Pokémon, and more.',
    admissionPrice: '$10',
  },
  {
    id: 'pittsburgh500-mar-2026',
    name: 'Sports Card Showcase: The Pittsburgh 500',
    location: 'Monroeville, PA',
    venue: 'Monroeville Convention Center',
    lat: 40.4281,
    lng: -79.7604,
    startDate: '2026-03-27',
    endDate: '2026-03-29',
    recurrence: 'Annual',
    tables: 525,
    size: 'mega',
    url: null,
    description: '525+ tables. Pittsburgh\'s mega show at the Monroeville Convention Center. Free admission.',
    admissionPrice: 'Free',
  },
  {
    id: 'derby-city-oct-2026',
    name: 'Derby City Card Show',
    location: 'Louisville, KY',
    venue: 'Kentucky International Convention Center',
    lat: 38.2527,
    lng: -85.7585,
    startDate: '2026-10-08',
    endDate: '2026-10-08',
    recurrence: '2x per year',
    tables: 500,
    size: 'mega',
    url: null,
    description: '500+ tables. Kentucky\'s flagship card show in downtown Louisville. Major Midwest draw.',
    admissionPrice: '$10',
  },
  {
    id: 'midamerica-jul-2026',
    name: 'Mid-America Center Card Show',
    location: 'Council Bluffs, IA',
    venue: 'Mid-America Center',
    lat: 41.2285,
    lng: -95.8517,
    startDate: '2026-07-24',
    endDate: '2026-07-26',
    recurrence: '2x per year',
    tables: 500,
    size: 'mega',
    url: null,
    description: '500+ tables. Iowa\'s mega show draws dealers from across the Midwest. Omaha metro accessible.',
    admissionPrice: '$10',
  },
  {
    id: 'midamerica-oct-2026',
    name: 'Mid-America Center Card Show',
    location: 'Council Bluffs, IA',
    venue: 'Mid-America Center',
    lat: 41.2285,
    lng: -95.8517,
    startDate: '2026-10-23',
    endDate: '2026-10-25',
    recurrence: '2x per year',
    tables: 500,
    size: 'mega',
    url: null,
    description: '500+ tables. Fall edition of Iowa\'s largest show. Prime pre-holiday inventory.',
    admissionPrice: '$10',
  },
  {
    id: 'frontrow-portland-jun-2026',
    name: 'Front Row Card Show',
    location: 'Portland, OR',
    venue: 'Oregon Convention Center',
    lat: 45.5282,
    lng: -122.6629,
    startDate: '2026-06-13',
    endDate: '2026-06-14',
    recurrence: 'Annual',
    tables: 450,
    size: 'mega',
    url: 'https://frontrowcardshow.com',
    description: '450 tables. Front Row\'s Pacific Northwest mega show at the Oregon Convention Center.',
    admissionPrice: '$10',
  },
  {
    id: 'frontrow-tacoma-apr-2026',
    name: 'Front Row Card Show',
    location: 'Tacoma, WA',
    venue: 'Greater Tacoma Convention Center',
    lat: 47.2495,
    lng: -122.4382,
    startDate: '2026-04-11',
    endDate: '2026-04-12',
    recurrence: 'Annual',
    tables: 440,
    size: 'mega',
    url: 'https://frontrowcardshow.com',
    description: '440 tables. Major PNW show — the biggest card event in Washington state.',
    admissionPrice: '$10',
  },
  {
    id: 'gettysburg-may-2026',
    name: 'National Battlefield Card Classic',
    location: 'Gettysburg, PA',
    venue: 'All-Star Sports Complex',
    lat: 39.8309,
    lng: -77.2311,
    startDate: '2026-05-23',
    endDate: '2026-05-24',
    recurrence: 'Annual',
    tables: 450,
    size: 'mega',
    url: null,
    description: '450 tables. Central PA mega show at the All-Star Sports Complex. Growing fast.',
    admissionPrice: '$10',
  },
  {
    id: 'westminster-may-2026',
    name: 'The West Monster Show',
    location: 'Westminster, MD',
    venue: 'TownMall of Westminster',
    lat: 39.5754,
    lng: -76.9958,
    startDate: '2026-05-02',
    endDate: '2026-05-02',
    recurrence: '2-3x per year',
    tables: 400,
    size: 'mega',
    url: null,
    description: '400+ tables. Maryland mega show at TownMall. Sports cards and TCGs under one roof.',
    admissionPrice: '$10',
  },
  {
    id: 'csa-chantilly-apr-2026',
    name: 'CSA Sports Card & Memorabilia Convention',
    location: 'Chantilly, VA',
    venue: 'Dulles Expo Center',
    lat: 38.8628,
    lng: -77.4435,
    startDate: '2026-04-10',
    endDate: '2026-04-12',
    recurrence: '3x per year',
    tables: 400,
    size: 'mega',
    url: null,
    description: '400+ tables. Premier DC-area convention with Beckett Authentication and celebrity autograph guests.',
    admissionPrice: '$15',
  },
  {
    id: 'csa-chantilly-jun-2026',
    name: 'CSA Sports Card & Memorabilia Convention',
    location: 'Chantilly, VA',
    venue: 'Dulles Expo Center',
    lat: 38.8628,
    lng: -77.4435,
    startDate: '2026-06-26',
    endDate: '2026-06-28',
    recurrence: '3x per year',
    tables: 400,
    size: 'mega',
    url: null,
    description: '400+ tables. Summer edition of the DC-area mega convention at Dulles Expo.',
    admissionPrice: '$15',
  },
  {
    id: 'csa-chantilly-oct-2026',
    name: 'CSA Sports Card & Memorabilia Convention',
    location: 'Chantilly, VA',
    venue: 'Dulles Expo Center',
    lat: 38.8628,
    lng: -77.4435,
    startDate: '2026-10-16',
    endDate: '2026-10-18',
    recurrence: '3x per year',
    tables: 400,
    size: 'mega',
    url: null,
    description: '400+ tables. Fall edition of the DC-area mega convention at Dulles Expo.',
    admissionPrice: '$15',
  },
  {
    id: 'global-sports-sc-jun-2026',
    name: 'Global Sports Card Show',
    location: 'Spartanburg, SC',
    venue: 'Global Sports',
    lat: 34.9496,
    lng: -81.9320,
    startDate: '2026-06-26',
    endDate: '2026-06-27',
    recurrence: '2x per year',
    tables: 400,
    size: 'mega',
    url: null,
    description: '400+ tables. Largest show in the Carolinas region. Free admission.',
    admissionPrice: 'Free',
  },
  {
    id: 'ntx-fortworth-apr-2026',
    name: 'NTX Fort Worth Card Show',
    location: 'Fort Worth, TX',
    venue: 'Amon G. Carter Jr. Exhibits Hall',
    lat: 32.7473,
    lng: -97.3348,
    startDate: '2026-04-18',
    endDate: '2026-04-19',
    recurrence: '2-3x per year',
    tables: 400,
    size: 'mega',
    url: null,
    description: '400+ tables. Major North Texas show in Fort Worth\'s premier exhibit hall.',
    admissionPrice: '$5',
  },

  // ── MAJOR (200–399 tables) ──

  {
    id: 'frontrow-sandiego-apr-2026',
    name: 'Front Row Card Show',
    location: 'San Diego, CA',
    venue: 'Town & Country Resort',
    lat: 32.7682,
    lng: -117.2053,
    startDate: '2026-04-25',
    endDate: '2026-04-26',
    recurrence: '2x per year',
    tables: 425,
    size: 'mega',
    url: 'https://frontrowcardshow.com',
    description: '425 tables. Front Row\'s SoCal mega show at the Town & Country Resort.',
    admissionPrice: '$10',
  },
  {
    id: 'frontrow-atlanta-mar-2026',
    name: 'Front Row Card Show',
    location: 'Atlanta, GA',
    venue: 'Cobb Convention Center',
    lat: 33.9358,
    lng: -84.5194,
    startDate: '2026-03-28',
    endDate: '2026-03-29',
    recurrence: 'Annual',
    tables: 350,
    size: 'major',
    url: 'https://frontrowcardshow.com',
    description: '350 tables. Atlanta\'s largest card show at the Cobb Convention Center.',
    admissionPrice: '$10',
  },
  {
    id: 'bestflippin-boston-may-2026',
    name: 'The Best Flippin\' TCG Card Show',
    location: 'Boston, MA',
    venue: 'Hynes Convention Center',
    lat: 42.3472,
    lng: -71.0846,
    startDate: '2026-05-02',
    endDate: '2026-05-03',
    recurrence: 'Annual',
    tables: 375,
    size: 'major',
    url: null,
    description: '375 tables. Boston\'s biggest show at the Hynes Convention Center. Sports & TCG focused.',
    admissionPrice: '$20',
  },
  {
    id: 'oc-cardshow-ca-mar-2026',
    name: 'OC Card Show',
    location: 'Costa Mesa, CA',
    venue: 'OC Fair & Event Center',
    lat: 33.6751,
    lng: -117.9010,
    startDate: '2026-03-21',
    endDate: '2026-03-22',
    recurrence: '3-4x per year',
    tables: 350,
    size: 'major',
    url: null,
    description: '350 tables. Orange County\'s flagship show. One of the top SoCal card events outside of West Coast Card Show.',
    admissionPrice: '$10',
  },
  {
    id: 'sd-cardshow-mar-2026',
    name: 'SD Card Show',
    location: 'San Diego, CA',
    venue: 'Del Mar Fairgrounds',
    lat: 32.9594,
    lng: -117.2653,
    startDate: '2026-03-14',
    endDate: '2026-03-15',
    recurrence: 'Monthly',
    tables: 300,
    size: 'major',
    url: null,
    description: '140-300 tables depending on the date. San Diego\'s recurring show at the Del Mar Fairgrounds.',
    admissionPrice: '$10',
  },
  {
    id: 'charlotte-mar-2026',
    name: 'Sports Wax Promotions Card Show',
    location: 'Charlotte, NC',
    venue: 'Blume Studios',
    lat: 35.2271,
    lng: -80.8431,
    startDate: '2026-03-20',
    endDate: '2026-03-21',
    recurrence: '3-4x per year',
    tables: 300,
    size: 'major',
    url: 'https://sportswaxpromotions.com',
    description: '300 tables. Charlotte\'s premier card show. Sports cards only.',
    admissionPrice: '$10',
  },
  {
    id: 'myrtle-beach-may-2026',
    name: 'Myrtle Beach Sports Cards & Pokémon Expo',
    location: 'Myrtle Beach, SC',
    venue: 'John T Rhodes Sports Center',
    lat: 33.6891,
    lng: -78.8867,
    startDate: '2026-05-22',
    endDate: '2026-05-23',
    recurrence: 'Quarterly',
    tables: 300,
    size: 'major',
    url: null,
    description: '300 tables. Beach vacation meets card show. Sports and Pokémon at the Myrtle Beach Sports Center.',
    admissionPrice: '$10',
  },
  {
    id: 'ntx-lewisville-apr-2026',
    name: 'NTX Sports Card Show',
    location: 'Lewisville, TX',
    venue: 'NTX Arena',
    lat: 33.0462,
    lng: -96.9941,
    startDate: '2026-04-11',
    endDate: '2026-04-12',
    recurrence: '3-4x per year',
    tables: 300,
    size: 'major',
    url: null,
    description: '300+ tables. Growing North Texas show in Lewisville — complementing Dallas Card Show.',
    admissionPrice: '$5',
  },
  {
    id: 'atxnorth-may-2026',
    name: 'ATX North Card Show',
    location: 'Belton, TX',
    venue: 'Cadence Bank Center',
    lat: 31.0561,
    lng: -97.4643,
    startDate: '2026-05-09',
    endDate: '2026-05-10',
    recurrence: '2x per year',
    tables: 350,
    size: 'major',
    url: null,
    description: '350+ tables. Central Texas mega show between Austin and Waco.',
    admissionPrice: '$5',
  },
  {
    id: 'lexington-ky-dec-2026',
    name: 'Central Bank Center Card Show',
    location: 'Lexington, KY',
    venue: 'Central Bank Center Exhibit Hall',
    lat: 38.0464,
    lng: -84.4970,
    startDate: '2026-12-04',
    endDate: '2026-12-04',
    recurrence: 'Annual',
    tables: 300,
    size: 'major',
    url: null,
    description: '300+ tables. Lexington\'s convention center show. Great holiday buying opportunity.',
    admissionPrice: '$10',
  },
  {
    id: 'flip-huntsville-mar-2026',
    name: 'The Flip Sports Card & Collectibles Show',
    location: 'Huntsville, AL',
    venue: 'Von Braun Center',
    lat: 34.7304,
    lng: -86.5861,
    startDate: '2026-03-28',
    endDate: '2026-03-29',
    recurrence: '2x per year',
    tables: 300,
    size: 'major',
    url: null,
    description: '300+ tables. Alabama\'s largest show at the Von Braun Center in Huntsville.',
    admissionPrice: '$7',
  },
  {
    id: 'bestflippin-baltimore-apr-2026',
    name: 'The Best Flippin\' TCG Card Show',
    location: 'Baltimore, MD',
    venue: 'Baltimore Convention Center',
    lat: 39.2868,
    lng: -76.6163,
    startDate: '2026-04-11',
    endDate: '2026-04-12',
    recurrence: 'Annual',
    tables: 275,
    size: 'major',
    url: null,
    description: '275 tables. Major mid-Atlantic show in downtown Baltimore. Sports & TCG.',
    admissionPrice: '$15',
  },
  {
    id: 'baltimore-cardshow-may-2026',
    name: 'The Baltimore Card Show',
    location: 'Baltimore, MD',
    venue: 'Chesapeake Employers Insurance Arena (UMBC)',
    lat: 39.2556,
    lng: -76.7148,
    startDate: '2026-05-16',
    endDate: '2026-05-17',
    recurrence: '2x per year',
    tables: 250,
    size: 'major',
    url: null,
    description: '250+ tables at the UMBC arena. Baltimore\'s growing flagship card show.',
    admissionPrice: '$10',
  },
  {
    id: 'katy-apr-2026',
    name: 'Katy Sports Card Show',
    location: 'Katy, TX',
    venue: 'Merrell Center',
    lat: 29.7858,
    lng: -95.8247,
    startDate: '2026-04-18',
    endDate: '2026-04-19',
    recurrence: '2-3x per year',
    tables: 276,
    size: 'major',
    url: 'https://katysportscardshow.com',
    description: '276 tables. West Houston/Katy\'s largest show at the Merrell Center. Free admission.',
    admissionPrice: 'Free',
  },
  {
    id: 'htx-cardshow-mar-2026',
    name: 'HTX Card Show',
    location: 'Montgomery, TX',
    venue: 'Margaritaville Lake Conroe',
    lat: 30.3835,
    lng: -95.6849,
    startDate: '2026-03-21',
    endDate: '2026-03-22',
    recurrence: '3-4x per year',
    tables: 250,
    size: 'major',
    url: null,
    description: '250+ tables. North Houston area show at the Margaritaville resort. Growing fast.',
    admissionPrice: '$1',
  },
  {
    id: 'atx-austin-apr-2026',
    name: 'ATX Card Show',
    location: 'Austin, TX',
    venue: 'Hilton Austin',
    lat: 30.2649,
    lng: -97.7390,
    startDate: '2026-04-25',
    endDate: '2026-04-25',
    recurrence: '2-3x per year',
    tables: 250,
    size: 'major',
    url: null,
    description: '250+ tables. Austin\'s flagship show in the heart of downtown.',
    admissionPrice: '$5',
  },
  {
    id: 'conroe-mar-2026',
    name: 'Conroe Sports Cards & Collectibles Show',
    location: 'Conroe, TX',
    venue: 'Hyatt Regency Conroe',
    lat: 30.3119,
    lng: -95.4561,
    startDate: '2026-03-21',
    endDate: '2026-03-22',
    recurrence: '2x per year',
    tables: 220,
    size: 'major',
    url: null,
    description: '220 tables. North Houston metro show. Free admission.',
    admissionPrice: 'Free',
  },
  {
    id: 'castine-la-may-2026',
    name: 'Castine Center Card Show',
    location: 'Mandeville, LA',
    venue: 'Castine Center',
    lat: 30.3580,
    lng: -90.0683,
    startDate: '2026-05-02',
    endDate: '2026-05-02',
    recurrence: 'Quarterly',
    tables: 250,
    size: 'major',
    url: null,
    description: '250+ tables. Louisiana\'s largest card show on the North Shore. Covers the New Orleans metro.',
    admissionPrice: '$5',
  },
  {
    id: 'texoma-durant-apr-2026',
    name: 'Texoma Trading Card Expo',
    location: 'Durant, OK',
    venue: 'Choctaw Casino & Resort Event Center',
    lat: 33.9934,
    lng: -96.3923,
    startDate: '2026-04-24',
    endDate: '2026-04-26',
    recurrence: 'Annual',
    tables: 250,
    size: 'major',
    url: 'https://texomaexpo.com',
    description: '250 tables. Oklahoma\'s premier show at Choctaw Casino. Draws Dallas/Fort Worth crowd too.',
    admissionPrice: '$10',
  },
  {
    id: 'stcharles-may-2026',
    name: 'St. Charles Convention Center Card Show',
    location: 'St. Charles, MO',
    venue: 'St. Charles Convention Center',
    lat: 38.7881,
    lng: -90.4974,
    startDate: '2026-05-22',
    endDate: '2026-05-24',
    recurrence: '2x per year',
    tables: 240,
    size: 'major',
    url: null,
    description: '240+ tables. Missouri\'s biggest show in the St. Louis metro. Free admission.',
    admissionPrice: 'Free',
  },
  {
    id: 'stcharles-sep-2026',
    name: 'St. Charles Convention Center Card Show',
    location: 'St. Charles, MO',
    venue: 'St. Charles Convention Center',
    lat: 38.7881,
    lng: -90.4974,
    startDate: '2026-09-25',
    endDate: '2026-09-27',
    recurrence: '2x per year',
    tables: 240,
    size: 'major',
    url: null,
    description: '240+ tables. Fall edition. Free admission draws collectors from across Missouri and Illinois.',
    admissionPrice: 'Free',
  },
  {
    id: 'shawnee-ks-apr-2026',
    name: 'Shawnee GAS Station Card Show',
    location: 'Shawnee, KS',
    venue: 'Shawnee GAS Station',
    lat: 39.0228,
    lng: -94.7151,
    startDate: '2026-04-24',
    endDate: '2026-04-26',
    recurrence: 'Annual',
    tables: 300,
    size: 'major',
    url: null,
    description: '300+ tables. Kansas City area mega show. Free admission.',
    admissionPrice: 'Free',
  },
  {
    id: 'cherryhill-nj-mar-2026',
    name: 'Cherry Hill Card Expo',
    location: 'Cherry Hill, NJ',
    venue: 'DoubleTree by Hilton',
    lat: 39.9318,
    lng: -75.0010,
    startDate: '2026-03-21',
    endDate: '2026-03-22',
    recurrence: '2x per year',
    tables: 225,
    size: 'major',
    url: 'https://fishtowncardshow.com',
    description: '225+ tables. South Jersey\'s premier show. Easy access from Philly.',
    admissionPrice: '$10',
  },
  {
    id: 'collector-expo-boxborough-apr-2026',
    name: 'The Collector Expo',
    location: 'Boxborough, MA',
    venue: 'Boxboro Regency Conference Center',
    lat: 42.4912,
    lng: -71.5154,
    startDate: '2026-04-04',
    endDate: '2026-04-04',
    recurrence: 'Quarterly',
    tables: 225,
    size: 'major',
    url: null,
    description: '225 tables. Central Massachusetts show drawing Boston metro collectors.',
    admissionPrice: '$10',
  },
  {
    id: 'vabeach-may-2026',
    name: 'Virginia Beach Card Expo',
    location: 'Virginia Beach, VA',
    venue: 'Virginia Beach Fieldhouse',
    lat: 36.8116,
    lng: -76.0553,
    startDate: '2026-05-02',
    endDate: '2026-05-03',
    recurrence: '2x per year',
    tables: 250,
    size: 'major',
    url: null,
    description: '250 tables. Hampton Roads/Tidewater area\'s biggest show. Free admission.',
    admissionPrice: 'Free',
  },
  {
    id: 'rva-expo-may-2026',
    name: 'RVA Expo Regional Card Show',
    location: 'Henrico, VA',
    venue: 'Richmond Raceway Complex',
    lat: 37.5938,
    lng: -77.4195,
    startDate: '2026-05-30',
    endDate: '2026-05-31',
    recurrence: '2x per year',
    tables: 210,
    size: 'major',
    url: null,
    description: '210 tables. Richmond metro\'s flagship show at the Raceway Complex. Free admission.',
    admissionPrice: 'Free',
  },
  {
    id: 'bristol-va-apr-2026',
    name: 'Tri Cities Card Show',
    location: 'Bristol, VA',
    venue: 'Hard Rock Hotel and Casino',
    lat: 36.6354,
    lng: -82.1607,
    startDate: '2026-04-18',
    endDate: '2026-04-18',
    recurrence: '2x per year',
    tables: 225,
    size: 'major',
    url: null,
    description: '225 tables at the Hard Rock. Covers the VA/TN border Tri-Cities area.',
    admissionPrice: '$5',
  },
  {
    id: 'brotherly-love-apr-2026',
    name: 'Brotherly Love Card Show',
    location: 'Philadelphia, PA',
    venue: 'Live Casino & Hotel Philadelphia',
    lat: 39.9048,
    lng: -75.1689,
    startDate: '2026-04-04',
    endDate: '2026-04-04',
    recurrence: '2-3x per year',
    tables: 200,
    size: 'major',
    url: null,
    description: '200 tables. Philly\'s casino card show. South Philly location near the stadiums.',
    admissionPrice: '$10',
  },
  {
    id: 'hollywood-casino-pa-apr-2026',
    name: 'Hollywood Casino Card Show',
    location: 'Grantville, PA',
    venue: 'Hollywood Casino',
    lat: 40.3573,
    lng: -76.7188,
    startDate: '2026-04-25',
    endDate: '2026-04-25',
    recurrence: '2x per year',
    tables: 200,
    size: 'major',
    url: null,
    description: '200 tables. Central PA show at the Hollywood Casino. Free admission.',
    admissionPrice: 'Free',
  },
  {
    id: 'eastcoast-uncasville-jun-2026',
    name: 'East Coast Collectibles Convention',
    location: 'Uncasville, CT',
    venue: 'Mohegan Sun',
    lat: 41.4312,
    lng: -72.0910,
    startDate: '2026-06-20',
    endDate: '2026-06-21',
    recurrence: 'Annual',
    tables: 300,
    size: 'major',
    url: null,
    description: '300+ tables at Mohegan Sun Casino. Connecticut\'s largest summer card event.',
    admissionPrice: '$10',
  },
  {
    id: 'gg2-ok-apr-2026',
    name: 'GG2 Sports Cards Show',
    location: 'Broken Arrow, OK',
    venue: 'Stoney Creek Hotel',
    lat: 36.0526,
    lng: -95.7908,
    startDate: '2026-04-03',
    endDate: '2026-04-05',
    recurrence: '2x per year',
    tables: 200,
    size: 'major',
    url: null,
    description: '200 tables. Tulsa-area show. Free admission draws Oklahoma and Arkansas collectors.',
    admissionPrice: 'Free',
  },
  {
    id: 'simpsonville-sc-mar-2026',
    name: 'Simpsonville Cards & Collectibles Show',
    location: 'Simpsonville, SC',
    venue: 'Simpsonville Senior Activity Center',
    lat: 34.7371,
    lng: -82.2543,
    startDate: '2026-03-07',
    endDate: '2026-03-07',
    recurrence: '2x per year',
    tables: 200,
    size: 'major',
    url: null,
    description: '200 tables. Upstate South Carolina\'s main recurring show.',
    admissionPrice: '$3',
  },
  {
    id: 'greenday-wi-apr-2026',
    name: 'The Green Bay Card Show',
    location: 'Green Bay, WI',
    venue: 'KI Convention Center',
    lat: 44.5133,
    lng: -88.0133,
    startDate: '2026-04-19',
    endDate: '2026-04-19',
    recurrence: '3x per year',
    tables: 200,
    size: 'major',
    url: null,
    description: '200 tables in Packers country. Strong football and hockey card inventory. Free admission.',
    admissionPrice: 'Free',
  },
  {
    id: 'hagerstown-md-apr-2026',
    name: 'Hagerstown Sports Card & TCG Show',
    location: 'Hagerstown, MD',
    venue: 'Valley Mall',
    lat: 39.6418,
    lng: -77.7200,
    startDate: '2026-04-18',
    endDate: '2026-04-19',
    recurrence: '2-3x per year',
    tables: 200,
    size: 'major',
    url: null,
    description: '200 tables. Western Maryland show. Free admission.',
    admissionPrice: 'Free',
  },

  // ── REGIONAL (70–199 tables) ──

  {
    id: 'winstonsalem-apr-2026',
    name: 'Pow Productions Card Show',
    location: 'Winston-Salem, NC',
    venue: 'Truist Stadium',
    lat: 36.0999,
    lng: -80.2442,
    startDate: '2026-04-04',
    endDate: '2026-04-04',
    recurrence: '3-4x per year',
    tables: 180,
    size: 'regional',
    url: 'https://powcardshows.com',
    description: '180+ tables at the minor league ballpark. One of several Pow Productions NC shows.',
    admissionPrice: '$5',
  },
  {
    id: 'ne-expo-quincy-mar-2026',
    name: 'Northeast Sports Card Expo',
    location: 'Quincy, MA',
    venue: 'Marriott Boston Quincy',
    lat: 42.2529,
    lng: -71.0023,
    startDate: '2026-03-28',
    endDate: '2026-03-29',
    recurrence: '2x per year',
    tables: 180,
    size: 'regional',
    url: null,
    description: '180 tables. South of Boston show. Different from the Stamford CT Northeast Expo.',
    admissionPrice: '$15',
  },
  {
    id: 'emerald-sq-ma-mar-2026',
    name: 'Emerald Square Mall Card Show',
    location: 'North Attleboro, MA',
    venue: 'Emerald Square Mall',
    lat: 41.9612,
    lng: -71.3379,
    startDate: '2026-03-14',
    endDate: '2026-03-15',
    recurrence: 'Monthly',
    tables: 175,
    size: 'regional',
    url: null,
    description: '175 tables. New England\'s biggest free-admission monthly show. RI/MA border.',
    admissionPrice: 'Free',
  },
  {
    id: 'evansville-in-may-2026',
    name: 'Southwest Indiana Card Show',
    location: 'Evansville, IN',
    venue: 'National Guard Armory',
    lat: 37.9716,
    lng: -87.5711,
    startDate: '2026-05-01',
    endDate: '2026-05-02',
    recurrence: '4x per year',
    tables: 160,
    size: 'regional',
    url: null,
    description: '160 tables. Southern Indiana\'s main show. Draws collectors from IN, KY, and IL.',
    admissionPrice: '$3',
  },
  {
    id: 'bronco-bash-mar-2026',
    name: 'I-69 Bronco Bash',
    location: 'Daleville, IN',
    venue: 'Daleville High School',
    lat: 40.1211,
    lng: -85.5600,
    startDate: '2026-03-27',
    endDate: '2026-03-28',
    recurrence: 'Annual',
    tables: 250,
    size: 'major',
    url: null,
    description: '250+ tables. Central Indiana sleeper hit. Free admission at the high school gym.',
    admissionPrice: 'Free',
  },
  {
    id: 'crownpoint-in-mar-2026',
    name: 'Crown Point Card Show',
    location: 'Crown Point, IN',
    venue: 'Lake County Fairgrounds',
    lat: 41.4170,
    lng: -87.3653,
    startDate: '2026-03-28',
    endDate: '2026-03-28',
    recurrence: '2x per year',
    tables: 125,
    size: 'regional',
    url: null,
    description: '125+ tables. NW Indiana show near Chicago. Free admission.',
    admissionPrice: 'Free',
  },
  {
    id: 'scottsboro-al-jun-2026',
    name: 'Scottsboro Sports Card & Memorabilia Show',
    location: 'Scottsboro, AL',
    venue: 'Goose Pond Civic Center',
    lat: 34.6723,
    lng: -86.0341,
    startDate: '2026-06-13',
    endDate: '2026-06-13',
    recurrence: 'Quarterly',
    tables: 150,
    size: 'regional',
    url: null,
    description: '150+ tables. Northeast Alabama\'s recurring show. Free admission.',
    admissionPrice: 'Free',
  },
  {
    id: 'greatplains-ne-jun-2026',
    name: 'Great Plains Card Convention',
    location: 'Omaha, NE',
    venue: 'CHI Health Center',
    lat: 41.2524,
    lng: -95.9280,
    startDate: '2026-06-13',
    endDate: '2026-06-14',
    recurrence: 'Annual',
    tables: 149,
    size: 'regional',
    url: null,
    description: '149 tables. Nebraska\'s only major show. Draws from Omaha and Lincoln metros.',
    admissionPrice: '$10',
  },
  {
    id: 'flipnbacon-portland-apr-2026',
    name: 'FlipnBacon Cards & Collectibles Show',
    location: 'Portland, OR',
    venue: 'DoubleTree by Hilton Portland',
    lat: 45.5310,
    lng: -122.6565,
    startDate: '2026-04-18',
    endDate: '2026-04-19',
    recurrence: '2x per year',
    tables: 150,
    size: 'regional',
    url: null,
    description: '150+ tables. Portland\'s local show. Good warm-up before the Front Row mega in June.',
    admissionPrice: '$5',
  },
  {
    id: 'iowa-cardshow-jul-2026',
    name: 'Iowa Card Show',
    location: 'West Des Moines, IA',
    venue: 'MidAmerican RecPlex',
    lat: 41.5772,
    lng: -93.7113,
    startDate: '2026-07-19',
    endDate: '2026-07-19',
    recurrence: 'Annual',
    tables: 125,
    size: 'regional',
    url: null,
    description: '125 tables. Des Moines area show. Free admission.',
    admissionPrice: 'Free',
  },
  {
    id: 'shreveport-la-apr-2026',
    name: 'Shreveport Card Show',
    location: 'Shreveport, LA',
    venue: 'AcroSports and The Fieldhouse',
    lat: 32.5252,
    lng: -93.7502,
    startDate: '2026-04-11',
    endDate: '2026-04-12',
    recurrence: 'Annual',
    tables: 115,
    size: 'regional',
    url: null,
    description: '115 tables. North Louisiana\'s card show. Under-12 free.',
    admissionPrice: '$5',
  },
  {
    id: 'mooresville-nc-mar-2026',
    name: 'HobbyMan Events Card Show',
    location: 'Mooresville, NC',
    venue: 'Charles Mack Citizen Center',
    lat: 35.5849,
    lng: -80.8101,
    startDate: '2026-03-14',
    endDate: '2026-03-14',
    recurrence: '2x per year',
    tables: 125,
    size: 'regional',
    url: null,
    description: '125 tables. Lake Norman area show north of Charlotte.',
    admissionPrice: '$5',
  },
  {
    id: 'greenville-sc-may-2026',
    name: 'Greenville Sports Cards & Pokémon Show',
    location: 'Greenville, SC',
    venue: 'Haywood Mall',
    lat: 34.8361,
    lng: -82.3668,
    startDate: '2026-05-09',
    endDate: '2026-05-09',
    recurrence: 'Bi-monthly',
    tables: 150,
    size: 'regional',
    url: null,
    description: '150 tables. Greenville\'s recurring mall show. Free admission.',
    admissionPrice: 'Free',
  },
  {
    id: 'goldsboro-nc-may-2026',
    name: 'Greater Goldsboro Collectibles Show',
    location: 'Goldsboro, NC',
    venue: 'The Maxwell Center',
    lat: 35.3849,
    lng: -78.0440,
    startDate: '2026-05-30',
    endDate: '2026-05-30',
    recurrence: 'Annual',
    tables: 150,
    size: 'regional',
    url: null,
    description: '150 tables. Eastern NC show. Free admission.',
    admissionPrice: 'Free',
  },
  {
    id: 'midatlantic-md-may-2026',
    name: 'Mid-Atlantic Sports Card Show',
    location: 'Silver Spring, MD',
    venue: 'Silver Spring Civic Center',
    lat: 38.9907,
    lng: -77.0261,
    startDate: '2026-05-03',
    endDate: '2026-05-03',
    recurrence: '2x per year',
    tables: 170,
    size: 'regional',
    url: 'https://mid-atlanticshow.com',
    description: '170 tables. DC suburb show. Easy Metro access for the entire DMV area.',
    admissionPrice: '$5',
  },
  {
    id: 'waukesha-wi-apr-2026',
    name: 'The Waukesha Card Show',
    location: 'Waukesha, WI',
    venue: 'Waukesha Expo Center',
    lat: 43.0117,
    lng: -88.2312,
    startDate: '2026-04-11',
    endDate: '2026-04-11',
    recurrence: 'Monthly',
    tables: 100,
    size: 'regional',
    url: 'https://waukeshacardshow.com',
    description: '100+ tables. Milwaukee suburb\'s recurring show. Just $2 admission.',
    admissionPrice: '$2',
  },
  {
    id: 'eauclaire-wi-apr-2026',
    name: 'Sports Card Extravaganza',
    location: 'Eau Claire, WI',
    venue: 'Best Western Plus',
    lat: 44.8113,
    lng: -91.4985,
    startDate: '2026-04-24',
    endDate: '2026-04-26',
    recurrence: '3x per year',
    tables: 125,
    size: 'regional',
    url: null,
    description: '125 tables. Western Wisconsin show. Free admission, 3-day format.',
    admissionPrice: 'Free',
  },
  {
    id: 'madison-wi-apr-2026',
    name: 'Madison Card Show',
    location: 'Madison, WI',
    venue: 'Madison Marriott South',
    lat: 43.0731,
    lng: -89.4012,
    startDate: '2026-04-26',
    endDate: '2026-04-26',
    recurrence: 'Monthly',
    tables: 120,
    size: 'regional',
    url: null,
    description: '120 tables. State capital show. Free admission.',
    admissionPrice: 'Free',
  },
  {
    id: 'jjallstar-ky-mar-2026',
    name: 'J&J Allstar Sports Card Show',
    location: 'Louisville, KY',
    venue: 'Our Mother of Sorrows Lyons Hall',
    lat: 38.2218,
    lng: -85.7246,
    startDate: '2026-03-07',
    endDate: '2026-03-07',
    recurrence: 'Bi-monthly',
    tables: 130,
    size: 'regional',
    url: null,
    description: '130 tables. Louisville\'s frequent community show. Free admission.',
    admissionPrice: 'Free',
  },
  {
    id: 'cuyahoga-oh-mar-2026',
    name: 'Cuyahoga Falls Sports Card & Pokémon Show',
    location: 'Cuyahoga Falls, OH',
    venue: 'Emidio and Sons Expo Center',
    lat: 41.1340,
    lng: -81.4845,
    startDate: '2026-03-21',
    endDate: '2026-03-22',
    recurrence: '2x per year',
    tables: 220,
    size: 'major',
    url: null,
    description: '220+ tables. Akron-area show. Free admission.',
    admissionPrice: 'Free',
  },
  {
    id: 'boardman-oh-mar-2026',
    name: 'Boardman Sportscards Show',
    location: 'Boardman, OH',
    venue: 'Boardman Plaza',
    lat: 41.0203,
    lng: -80.6687,
    startDate: '2026-03-06',
    endDate: '2026-03-08',
    recurrence: '2x per year',
    tables: 200,
    size: 'major',
    url: null,
    description: '200+ tables. Youngstown area show. Free admission. Strong Pittsburgh crossover crowd.',
    admissionPrice: 'Free',
  },
  {
    id: 'columbus-oh-mar-2026',
    name: 'Columbus Sports Card Show',
    location: 'Hilliard, OH',
    venue: 'Franklin County Fairgrounds',
    lat: 40.0334,
    lng: -83.1582,
    startDate: '2026-03-07',
    endDate: '2026-03-08',
    recurrence: '3x per year',
    tables: 150,
    size: 'regional',
    url: null,
    description: '150 tables. Columbus metro show. Free admission.',
    admissionPrice: 'Free',
  },
  {
    id: 'medina-oh-may-2026',
    name: 'Medina Card Show',
    location: 'Medina, OH',
    venue: 'Medina Fairgrounds',
    lat: 41.1381,
    lng: -81.8637,
    startDate: '2026-05-29',
    endDate: '2026-05-30',
    recurrence: '2x per year',
    tables: 200,
    size: 'major',
    url: null,
    description: '200 tables. Between Cleveland and Akron. Solid mid-Ohio show.',
    admissionPrice: '$5',
  },
  {
    id: 'supercon-queens-mar-2026',
    name: 'SUPERCON: Queens',
    location: 'Queens, NY',
    venue: 'Queens College',
    lat: 40.7362,
    lng: -73.8203,
    startDate: '2026-03-08',
    endDate: '2026-03-08',
    recurrence: 'Bi-monthly',
    tables: 100,
    size: 'regional',
    url: null,
    description: '100+ tables in NYC proper. One of the few shows inside the five boroughs.',
    admissionPrice: '$5',
  },
  {
    id: 'statenisland-mar-2026',
    name: 'Staten Island Card Show',
    location: 'Staten Island, NY',
    venue: 'Holy Rosary Gym',
    lat: 40.5834,
    lng: -74.0844,
    startDate: '2026-03-21',
    endDate: '2026-03-21',
    recurrence: 'Monthly',
    tables: 100,
    size: 'regional',
    url: null,
    description: '100 tables. NYC\'s Staten Island community show. Easy parking.',
    admissionPrice: '$5',
  },
  {
    id: 'asheville-nc-mar-2026',
    name: 'Pow Productions Asheville Card Show',
    location: 'Asheville, NC',
    venue: 'Asheville Mall',
    lat: 35.5581,
    lng: -82.5157,
    startDate: '2026-03-14',
    endDate: '2026-03-15',
    recurrence: 'Monthly',
    tables: 120,
    size: 'regional',
    url: 'https://powcardshows.com',
    description: '120+ tables. Western NC mountain city show. Free admission.',
    admissionPrice: 'Free',
  },
  {
    id: 'fishtown-philly-may-2026',
    name: 'Fishtown Card Show',
    location: 'Philadelphia, PA',
    venue: 'Rivers Casino Philadelphia',
    lat: 39.9673,
    lng: -75.1342,
    startDate: '2026-05-02',
    endDate: '2026-05-03',
    recurrence: '2x per year',
    tables: 150,
    size: 'regional',
    url: 'https://fishtowncardshow.com',
    description: '150+ tables at Rivers Casino. Fishtown/Northern Liberties vibe.',
    admissionPrice: '$10',
  },
  {
    id: '850-tallahassee-apr-2026',
    name: 'The 850 Card Show',
    location: 'Tallahassee, FL',
    venue: 'North Florida Fairgrounds',
    lat: 30.4383,
    lng: -84.2807,
    startDate: '2026-04-24',
    endDate: '2026-04-25',
    recurrence: 'Quarterly',
    tables: 150,
    size: 'regional',
    url: null,
    description: '150+ tables. North Florida/Panhandle\'s main show. Free admission.',
    admissionPrice: 'Free',
  },
  {
    id: 'heartland-il-apr-2026',
    name: 'Heart of Illinois Sports Card Expo',
    location: 'Bloomington, IL',
    venue: 'Interstate Center',
    lat: 40.4842,
    lng: -88.9937,
    startDate: '2026-04-10',
    endDate: '2026-04-11',
    recurrence: 'Annual',
    tables: 200,
    size: 'major',
    url: null,
    description: '200 tables. Central Illinois show between Chicago and St. Louis.',
    admissionPrice: '$3',
  },
  {
    id: 'rehoboth-de-may-2026',
    name: 'Rehoboth Beach Sports Card & TCG Show',
    location: 'Rehoboth Beach, DE',
    venue: 'Rehoboth Beach Convention Center',
    lat: 38.7210,
    lng: -75.0760,
    startDate: '2026-05-29',
    endDate: '2026-05-31',
    recurrence: 'Annual (Memorial Day)',
    tables: 124,
    size: 'regional',
    url: null,
    description: '124 tables. Beach town Memorial Day weekend show. Free admission. Vacation + cards.',
    admissionPrice: 'Free',
  },
  {
    id: 'gettysburg-pa-apr-2026',
    name: 'Gettysburg Sports Card Show',
    location: 'Gettysburg, PA',
    venue: 'Aspire Hotel',
    lat: 39.8309,
    lng: -77.2311,
    startDate: '2026-04-18',
    endDate: '2026-04-18',
    recurrence: '2x per year',
    tables: 125,
    size: 'regional',
    url: null,
    description: '125 tables. Historic town card show. Free admission.',
    admissionPrice: 'Free',
  },
  {
    id: 'harrisburg-pa-apr-2026',
    name: 'Harrisburg Sports Card & TCG Show',
    location: 'Summerdale, PA',
    venue: 'Central Penn College',
    lat: 40.3005,
    lng: -76.9362,
    startDate: '2026-04-04',
    endDate: '2026-04-04',
    recurrence: '2x per year',
    tables: 145,
    size: 'regional',
    url: null,
    description: '145 tables. Central PA show near Harrisburg. Free admission.',
    admissionPrice: 'Free',
  },
  {
    id: 'portland-or-mar-2026',
    name: 'Portland Card Show',
    location: 'Portland, OR',
    venue: 'DoubleTree by Hilton Portland',
    lat: 45.5310,
    lng: -122.6565,
    startDate: '2026-03-07',
    endDate: '2026-03-07',
    recurrence: 'Quarterly',
    tables: 100,
    size: 'regional',
    url: null,
    description: '100 tables. Portland\'s quarterly community show. Free admission.',
    admissionPrice: 'Free',
  },
  {
    id: 'maplewood-mn-oct-2026',
    name: 'Maplewood Mall Card Show',
    location: 'Maplewood, MN',
    venue: 'Maplewood Mall',
    lat: 45.0330,
    lng: -93.0252,
    startDate: '2026-10-16',
    endDate: '2026-10-18',
    recurrence: 'Annual',
    tables: 125,
    size: 'regional',
    url: null,
    description: '125 tables. Twin Cities east-side mall show. Free admission.',
    admissionPrice: 'Free',
  },
];

// ── Distance helpers ───────────────────────────────────────────────

/** Haversine distance in miles between two lat/lng points */
export function haversineDistance(
  lat1: number, lng1: number,
  lat2: number, lng2: number,
): number {
  const R = 3958.8; // Earth radius in miles
  const dLat = (lat2 - lat1) * Math.PI / 180;
  const dLng = (lng2 - lng1) * Math.PI / 180;
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1 * Math.PI / 180) *
    Math.cos(lat2 * Math.PI / 180) *
    Math.sin(dLng / 2) ** 2;
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

/** Zip code lookup via free zippopotam.us API — returns lat/lng or null */
export async function zipToCoords(zip: string): Promise<{ lat: number; lng: number } | null> {
  try {
    const res = await fetch(`https://api.zippopotam.us/us/${zip}`);
    if (!res.ok) return null;
    const data = await res.json();
    const place = data.places?.[0];
    if (!place) return null;
    return { lat: parseFloat(place.latitude), lng: parseFloat(place.longitude) };
  } catch {
    return null;
  }
}

/** Sort shows by distance from a point, returns shows with distance attached */
export function showsByDistance(
  lat: number,
  lng: number,
  shows: CardShow[] = CARD_SHOWS,
): (CardShow & { distance: number })[] {
  return shows
    .map(show => ({
      ...show,
      distance: Math.round(haversineDistance(lat, lng, show.lat, show.lng)),
    }))
    .sort((a, b) => a.distance - b.distance);
}

/** Format a date range nicely */
export function formatDateRange(start: string | null, end: string | null): string {
  if (!start) return 'Date TBA';
  const s = new Date(start + 'T00:00:00');
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  if (!end || start === end) {
    return `${months[s.getMonth()]} ${s.getDate()}, ${s.getFullYear()}`;
  }
  const e = new Date(end + 'T00:00:00');
  if (s.getMonth() === e.getMonth()) {
    return `${months[s.getMonth()]} ${s.getDate()}–${e.getDate()}, ${s.getFullYear()}`;
  }
  return `${months[s.getMonth()]} ${s.getDate()} – ${months[e.getMonth()]} ${e.getDate()}, ${s.getFullYear()}`;
}

/** Days until a show starts (negative = already happened) */
export function daysUntil(dateStr: string | null): number | null {
  if (!dateStr) return null;
  const now = new Date();
  now.setHours(0, 0, 0, 0);
  const target = new Date(dateStr + 'T00:00:00');
  return Math.ceil((target.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
}

/** Size label with emoji */
export function sizeLabel(size: ShowSize): { emoji: string; label: string } {
  switch (size) {
    case 'mega': return { emoji: '🏟️', label: 'Mega Show' };
    case 'major': return { emoji: '🎪', label: 'Major Show' };
    case 'regional': return { emoji: '📍', label: 'Regional Show' };
  }
}
